Create 667A - Pouring Rain
Waqar-107/Codeforces pull request #20
Opened 2022-09-21 16:07 UTC by Supporter09

Miss 667A so i added it ( AC tested on codeforces )

2022-09-21 19:14 UTC, Waqar-107 commented on A-set/667A. Pouring Rain.py
> +d,h,v,e = map(int, input().split())
Please add a new line after import. when you are declaring the variables, it's a good practice to use a space after the comma. Like, `d, h, v, e`

2022-09-21 19:15 UTC, Waqar-107 commented on A-set/667A. Pouring Rain.py
> +drink_s = (4*v)/(math.pi * (d**2))
Inconsistent indentation. `4*v` and `(math.pi * (d**2)`. Please make it `4 * v`

2022-09-21 19:15 UTC, Waqar-107 commented on A-set/667A. Pouring Rain.py
> +if drink_s > e:
Add a new line before this line

2022-09-21 19:17 UTC, Waqar-107 requested changes
I have added a few changes related to indentations. Please fix them so that we can merge this pull request. I know there are **old** codes in this repository with bad indentation but let us maintain indentation consistency.

2022-09-22 01:15 UTC, Supporter09 commented
Done!

2022-09-23 19:08 UTC, Waqar-107 commented on A-set/667A. Pouring Rain.py
> +drink_s = (4 * v)/(math.pi * (d**2))
`(4 * v) / (math.pi * (d**2))` - there should be spaces before and after the `/`

2022-09-23 19:09 UTC, Waqar-107 commented on A-set/667A. Pouring Rain.py
> +# from dust i have come, dust i will be
no need to add this

2022-09-23 19:09 UTC, Waqar-107 commented on A-set/667A. Pouring Rain.py
>      print(round(result,12))
please add a comma after `result`

2022-09-25 05:02 UTC, Waqar-107 approved these changes
Looks good. One friendly suggestion, in the industry, every problems solution is given in a different pull request. Suppose you are implementing a new feature and encounter a bug. You open a new ticket for that bug in the issue tracker and solve it in a different git branch and give a separate pull request.

2022-09-25 05:03 UTC, merged

2022-09-25 05:09 UTC, Supporter09 commented
Thanks!